
export default new Map([
["src/content/reference/data-nova-user-manual.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freference%2Fdata-nova-user-manual.mdoc&astroContentModuleFlag=true")],
["src/content/reference/data-nova-advanced-analytics-reference.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freference%2Fdata-nova-advanced-analytics-reference.mdoc&astroContentModuleFlag=true")],
["src/content/reference/data-nova-quick-start-guide.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Freference%2Fdata-nova-quick-start-guide.mdoc&astroContentModuleFlag=true")],
["src/content/articles/analyzing-financial-data-using-data-nova-for-business-strategy.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fanalyzing-financial-data-using-data-nova-for-business-strategy.mdoc&astroContentModuleFlag=true")],
["src/content/articles/advanced-data-cleaning-techniques-in-excel.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fadvanced-data-cleaning-techniques-in-excel.mdoc&astroContentModuleFlag=true")],
["src/content/articles/creating-custom-dashboards-in-excel-with-data-nova.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fcreating-custom-dashboards-in-excel-with-data-nova.mdoc&astroContentModuleFlag=true")],
["src/content/articles/integrating-data-nova-with-google-sheets-for-seamless-collaboration.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fintegrating-data-nova-with-google-sheets-for-seamless-collaboration.mdoc&astroContentModuleFlag=true")],
["src/content/articles/how-to-automate-reporting-with-data-nova-s-integration-tools.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fhow-to-automate-reporting-with-data-nova-s-integration-tools.mdoc&astroContentModuleFlag=true")],
["src/content/articles/mastering-ai-powered-insights-with-data-nova-s-smart-analysis-tools.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fmastering-ai-powered-insights-with-data-nova-s-smart-analysis-tools.mdoc&astroContentModuleFlag=true")],
["src/content/articles/transforming-raw-data-into-actionable-insights.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Ftransforming-raw-data-into-actionable-insights.mdoc&astroContentModuleFlag=true")],
["src/content/articles/unlocking-the-power-of-predictive-analytics.mdoc", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Funlocking-the-power-of-predictive-analytics.mdoc&astroContentModuleFlag=true")]]);
		