// This file is generated by Astro DB
declare module 'astro:db' {
	export const Feedback: import("@astrojs/db/runtime").Table<
		"Feedback",
		{"slug":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"slug","collection":"Feedback","primaryKey":true}},"helpful":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"helpful","collection":"Feedback","primaryKey":false,"optional":false,"default":0}},"notHelpful":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"notHelpful","collection":"Feedback","primaryKey":false,"optional":false,"default":0}}}
	>;
}
